### ISSUE TITLE
how i can use this with winform application

### ISSUE THREAD

**Issue by yaseenayahya** [smatsson/tusdotnet#1]
your wiki is empty please can you guide me how can i use this library with my winform application...

**Comment by smatsson** [comment]
Hi yaseenayahya

I'm not really sure what you are trying to achieve. Tusdotnet only handles the server side part of the protocol. Are you using your winforms app as a client to communicate with a server or does it run its own server? In the former case you will need to implement your own client lib. In the latter, it depends on how your server works.

**Comment by smatsson** [comment]
More than a month since my question and no reply. I'll close this for inactivity.
