### ISSUE TITLE
Uploaded files aren't accessible

### ISSUE THREAD

**Issue by uoziod** [smatsson/tusdotnet#14]
I'm using just exact usage example from the main GH page and it works for upload (although it works only through debug mode of VS, doesn't when I try to make upload through IIS application, but that's not the issue). One file is half-uploaded, I refresh page, and trying to continue, but since http://locahost:12345/files/4743819885739485834798324 is 404 it starts from scratch. Same problem for fully uploaded files - I see them in the upload folder, but they're not accessible by URL.
I'm running it along with Umbraco CMS if it's important.
Do you have any thoughts why's so?

**Comment by uoziod** [comment]
Apparently [this](https://github.com/smatsson/tusdotnet/wiki/Downloading-files) should help :)

**Comment by smatsson** [comment]
Glad to be of service! :D

**Comment by uoziod** [comment]
Although, I think it will be not an exceed information to mention that in order to make it working with IIS Application, best to prepend context.PathBase:

`
app.UseTus( context => new DefaultTusConfiguration
{
	Store = new TusDiskStore( @"C:\Temp" ),
	UrlPath = context.PathBase + "/files",
	...
`

**Comment by uoziod** [comment]
P.S: and also this:
```C#
				}
				else
				{
					await next.Invoke();
				}
```
is missing [here](https://github.com/smatsson/tusdotnet/wiki/Processing-a-file-once-the-file-upload-is-complete).

**Comment by smatsson** [comment]
context.PathBase is only needed if you run your application in a sub path in IIS, e.g. https://example.org/mysite/ and not if you run it directly under https://example.org. See http://owin.org/html/spec/owin-1.0.html#5-3-paths for how it works (context.PathBase corresponds with owin.RequestPathBase). I will update the example with this information, thanks! 

I'm not sure where you mean that ```await next.Invoke()``` should be added? OnUploadCompleteAsync is not a middleware (it's a callback) and there is no "next" to be called.
