### ISSUE TITLE
Original file name in OnUploadCompleteAsync

### ISSUE THREAD

**Issue by uoziod** [smatsson/tusdotnet#15]
Is there any way to get an original file name in OnUploadCompleteAsync callback?

**Comment by smatsson** [comment]
The protocol itself doesn't include file name but you can add it as metadata when creating the file upload. See https://github.com/smatsson/tusdotnet/blob/master/Source/TestSites/OwinTestApp/index.html#L30-L32

In OnUploadCompleteAsync you would then cast the store to a ITusReadableStore, grab the file and then get the metadata. See https://github.com/smatsson/tusdotnet/blob/master/Source/TestSites/OwinTestApp/Startup.cs#L73

Hope this helps. Feel free to ask any follow up questions.

**Comment by smatsson** [comment]
Was this issue resolved? :)
