### ISSUE TITLE
VS 2017 ASP.NET Core Web Application (.NET Framework)

### ISSUE THREAD

**Issue by VagyokC4** [smatsson/tusdotnet#18]
I am trying to install this package with VS 2017, into a new ASP.NET Core Web Application (.NET Framework) template.  I get the following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1929	'IApplicationBuilder' does not contain a definition for 'UseTus' and the best extension method overload 'TusAppBuilderExtensions.UseTus(IAppBuilder, Func<IOwinRequest, ITusConfiguration>)' requires a receiver of type 'IAppBuilder'	
```

IApplicationBuilder app resolves to Microsoft.AspNetCore.Builder.IApplicationBuilder, but it looks like your code is looking for OWIN namespace, not the Microsoft.AspNetCore namespace.

**Comment by smatsson** [comment]
@VagyokC4 I haven't seen this issue before. Could you please upload your project to this issue so that I can have a look?

**Comment by VagyokC4** [comment]
@smatsson Here is my media project.
[media.zip](https://github.com/smatsson/tusdotnet/files/1008939/media.zip)

**Comment by smatsson** [comment]
@VagyokC4 Thanks. This issue is quite peculiar. I have created a ASP.NET Core website on my machine using Visual Studio 2017. The csproj file for my project contains this: 
```
<PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
```

While your contain:
```
<PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
  </PropertyGroup>
```
netcoreapp1.1 runs perfectly on .NET 4.x. What version of the .NET Core SDK are you running? I'm using 1.0.4. You can check this in C:\Program Files\dotnet\sdk.

**Comment by VagyokC4** [comment]
@smatsson Yes, there are now two options in Visual Studio for ASP.NET Core:

- ASP.NET Core Web Application (.NET Core)
- ASP.NET Core Web Application (.NET Framework)

I am choosing the full .NET Framework stack for my ASP.NET Core Web Application.
As for SDK, the highest version I have in my sdk folder is 1.0.3

**Comment by smatsson** [comment]
Hmm wierd. I didn't have that option in my installation. What version of
Visual Studio are you running?

**Comment by VagyokC4** [comment]
```
Microsoft Visual Studio Community 2017
Version 15.1 (26403.7) Release
VisualStudio.15.Release/15.1.0+26403.7
Microsoft .NET Framework
Version 4.6.01586
```

**Comment by VagyokC4** [comment]
@smatsson 
```
Microsoft Visual Studio Community 2017
Version 15.1 (26403.7) Release
VisualStudio.15.Release/15.1.0+26403.7
Microsoft .NET Framework
Version 4.6.01586
```

**Comment by smatsson** [comment]
I'll have to investigate this a bit. Let me get back to you. :)

**Comment by VagyokC4** [comment]
@smatsson I'm getting an error finding the UseOwin (from solution #2).  
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IApplicationBuilder' does not contain a definition for 'UseOwin' and no extension method 'UseOwin' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)	media	C:\Users\Developer\Source\Repos\DRS-MEDIA\media\Startup.cs	64
```

**Comment by smatsson** [comment]
That's my bad I forgot to mention that you also need to install package
microsoft.aspnetcore.owin for the owin setup.

**Comment by smatsson** [comment]
@VagyokC4 Was this issue resolved?

**Comment by VagyokC4** [comment]
@smatsson I beleive so, yes.  I have been running with the .NET Standard, and I think with the missing library, solution number 2 would be working as well.

**Comment by smatsson** [comment]
@VagyokC4 Cool, I'll close this issue. Feel free to create a new one if you have more questions or comments.
