### ISSUE TITLE
Add support for Expiration

### ISSUE THREAD

**Issue by smatsson** [smatsson/tusdotnet#9]
http://tus.io/protocols/resumable-upload.html#expiration

Add an optional interface to be implemented by a data store, e.g. ITusExpirationStore. TusDiskStore should implement some kind of cleanup job that runs in the background removing expired files.

**Comment by VagyokC4** [comment]
@smatsson Is there an ETA for this?

**Comment by smatsson** [comment]
@VagyokC4 I have started working on it but there is currently no ETA. The problem is the automatic cleanup of exipred files as there are no good ways of running background jobs in .NET. I will probably go for a solution where the store can return the expired files to let the developer delete them as needed. Once that issue is solved it should be pretty straight forward to implement this extension.

**Comment by smatsson** [comment]
Update: Feature complete but some bugs need to be ironed out and documentation needs to be written.

**Comment by smatsson** [comment]
Cleanup job has been moved to dev code to reduce complexity of tusdotnet. Added documentation on the wiki on how to set it up: https://github.com/smatsson/tusdotnet/wiki/Removing-expired-incomplete-files
